
import { ProcessedArticle, TopicOption, SourceOption } from '@/types';

export const availableTopics: TopicOption[] = [
  { value: 'technology', label: 'Technology' },
  { value: 'business', label: 'Business' },
  { value: 'science', label: 'Science' },
  { value: 'health', label: 'Health' },
  { value: 'entertainment', label: 'Entertainment' },
  { value: 'sports', label: 'Sports' },
  { value: 'politics', label: 'Politics' },
  { value: 'world', label: 'World' },
];

export const availableSources: SourceOption[] = [
  { value: 'bbc-news', label: 'BBC News' },
  { value: 'cnn', label: 'CNN' },
  { value: 'the-verge', label: 'The Verge' },
  { value: 'wired', label: 'Wired' },
  { value: 'the-wall-street-journal', label: 'Wall Street Journal' },
  { value: 'techcrunch', label: 'TechCrunch' },
  { value: 'reuters', label: 'Reuters' },
  { value: 'the-new-york-times', label: 'New York Times' },
];

export const mockArticles: ProcessedArticle[] = [
  {
    id: '1',
    title: 'AI Tool Helps Identify New Materials for Sustainable Energy Applications',
    content: 'Scientists have developed a new AI-powered system that can predict the properties of materials before they are synthesized, significantly speeding up the discovery of new sustainable energy materials...',
    summary: 'A new AI system accelerates sustainable energy material discovery by predicting properties before synthesis, potentially revolutionizing renewable energy technology development.',
    url: 'https://example.com/article1',
    imageUrl: 'https://images.unsplash.com/photo-1532187643603-ba119ca4109e',
    source: 'The Verge',
    publishedAt: '2023-07-15T09:15:00Z',
    topics: ['technology', 'science'],
    sentiment: 'positive',
    explanation: 'The article discusses technological advancement with positive environmental implications.',
    isRead: false,
    isSaved: false,
  },
  {
    id: '2',
    title: 'Global Markets Decline Amid Renewed Inflation Concerns',
    content: 'Financial markets around the world experienced significant declines as new economic data suggested that inflation might be more persistent than previously anticipated...',
    summary: 'Global financial markets dropped following new data indicating more persistent inflation than expected, raising concerns about aggressive central bank policies and economic slowdown.',
    url: 'https://example.com/article2',
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3',
    source: 'Wall Street Journal',
    publishedAt: '2023-07-14T18:30:00Z',
    topics: ['business', 'world'],
    sentiment: 'negative',
    explanation: 'The article discusses economic downturn and market decline.',
    isRead: false,
    isSaved: true,
  },
  {
    id: '3',
    title: 'New Study Suggests Regular Exercise May Slow Brain Aging',
    content: 'A comprehensive study involving over 10,000 participants has found strong evidence that regular physical activity can slow down cognitive decline and protect against neurodegenerative diseases...',
    summary: 'A large study of 10,000+ participants found that regular exercise significantly slows cognitive decline and protects against neurodegenerative diseases, with even moderate activity showing benefits.',
    url: 'https://example.com/article3',
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b',
    source: 'BBC News',
    publishedAt: '2023-07-13T11:45:00Z',
    topics: ['health', 'science'],
    sentiment: 'positive',
    explanation: 'The article presents positive health findings that can improve quality of life.',
    isRead: true,
    isSaved: false,
  },
  {
    id: '4',
    title: 'Tech Companies Face Increasing Regulatory Scrutiny Over Data Practices',
    content: 'Major technology companies are under growing pressure from regulators worldwide regarding their data collection and processing practices...',
    summary: 'Major tech companies face intensifying global regulatory scrutiny over data practices, with potential fines reaching billions and new legislation requiring significant operational changes.',
    url: 'https://example.com/article4',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3',
    source: 'Reuters',
    publishedAt: '2023-07-12T14:20:00Z',
    topics: ['technology', 'business', 'politics'],
    sentiment: 'neutral',
    explanation: 'The article presents a balanced view of regulatory developments without strongly positive or negative framing.',
    isRead: false,
    isSaved: false,
  },
  {
    id: '5',
    title: 'New Smartphone Feature Uses AI to Detect Health Emergencies',
    content: 'A leading smartphone manufacturer has announced a new feature that uses artificial intelligence to detect potential health emergencies and automatically alert emergency services...',
    summary: 'A major smartphone maker introduced an AI feature that can detect health emergencies and automatically alert first responders, potentially saving lives through early intervention.',
    url: 'https://example.com/article5',
    imageUrl: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d',
    source: 'TechCrunch',
    publishedAt: '2023-07-11T09:30:00Z',
    topics: ['technology', 'health'],
    sentiment: 'positive',
    explanation: 'The article discusses a technological advancement with potentially life-saving implications.',
    isRead: false,
    isSaved: true,
  },
  {
    id: '6',
    title: 'Climate Scientists Warn of Accelerating Sea Level Rise',
    content: 'A new report from climate researchers indicates that sea levels are rising faster than previously projected, posing increased risks to coastal communities worldwide...',
    summary: 'Climate scientists warn that sea levels are rising faster than previously projected, threatening coastal communities globally and requiring urgent adaptation measures.',
    url: 'https://example.com/article6',
    imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05',
    source: 'New York Times',
    publishedAt: '2023-07-10T15:45:00Z',
    topics: ['science', 'world'],
    sentiment: 'negative',
    explanation: 'The article presents concerning environmental findings that pose risks to communities.',
    isRead: true,
    isSaved: false,
  },
];

export const userPreferences = {
  userId: 'user123',
  topics: ['technology', 'science', 'health'],
  keywords: ['AI', 'climate', 'renewable'],
  preferredSources: ['bbc-news', 'the-verge', 'wired'],
};
